name: dartevel
version: 0.0.1
description: >-
  a fullstack web framework like laravel for dart language
repository: https://github.com/dartevel/dartevel
authors:
  - Miladimos <miladimos@outlook.com>

homepage: https://dartevel.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartevel: 
    git: 
      url: https://github.com/dartevel/framework
      ref: master
  
dev_dependencies:
  test: ^1.17.11